Repository tnozicka/openshift-acme, pull requests merged in 2019-06, with the labels that each got.

#94 Remove travis CI (superseeded by openshift CI)
  .travis.yml
Labels: approved, lgtm, release-note-none, size/L

#95 Add GitHub templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/failing-test.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, release-note-none, retest-not-required-docs-only, size/M

#58 support http/https proxies #57
  pkg/controllers/route/exposer.go
Labels: approved, lgtm
