Repository tnozicka/openshift-acme, pull requests merged in 2020-04, with the labels that each got.

#118 Fix CI image format
  hack/ci-deploy.sh
Labels: approved, kind/failing-test, lgtm, priority/critical-urgent, queue/blocks-others, release-note-none

#116 Respect limitRanges when creating pods
  deploy/cluster-wide/clusterrole.yaml
  deploy/single-namespace/role.yaml
  deploy/specific-namespaces/role.yaml
  go.mod
  pkg/controller/route/route.go
  pkg/controller/route/route_test.go
  test/e2e/openshift/routes/routes.go
Labels: approved, kind/bug, lgtm, release-note

#114 Use current namespace and not hardcoded
  deploy/.diffs/single_namespace-deployment.yaml.diff
  deploy/.diffs/specific_namespaces-deployment.yaml.diff
  deploy/single-namespace/deployment.yaml
  deploy/specific-namespaces/deployment.yaml
Labels: approved, kind/cleanup, lgtm, ok-to-test, release-note

#122 Don't default images as they are now set in CI
  hack/ci-deploy.sh
Labels: approved, kind/cleanup, lgtm, release-note-none
